manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ziembski
      url-base: https://github.com/Ziembski
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: peahen-calling
      remote: ziembski
      repo-path: Peahen-Calling-for-ZMK
      revision: main
      path: modules/peahen-calling
  self:
    path: config
